DROP TABLE IF EXISTS BANK_ACCOUNTS;
CREATE TABLE BANK_ACCOUNTS (
id INT AUTO_INCREMENT PRIMARY KEY,
account_type VARCHAR(50) NOT NULL,
holder_name VARCHAR(100) NOT NULL,
status VARCHAR(50) NOT NULL,
creditable BOOLEAN NOT NULL,
debitable BOOLEAN NOT NULL,
version VARCHAR(20) NOT NULL,
bank_name VARCHAR (50) NOT NULL
);